# Freshman Year
The learning outcomes for this year are for students to: 

  1. Feel belonging as a student in our discipline, regardless of their personal background and future career goals.  
  2. Describe how designing and constructing civil infrastructure benefits society and how the tools of our disciplines can solve challenges to humanity. 
  3. Apply mathematics and basic physics to solve basic problems related to optimization and forces on static bodies. 
  4. Obtain meaningful business and engineering skills that could be useful in part-time research or internships. 

## CCE 101: Intro to CCE {#sec-introcce}
::: {.callout-note}
## Proposed Change
Offer the existing 1-credit hour CCE 101 class, but do not require it.
:::
The existing CCE 101 course is designed to *tell* students about the different
employment and study paths available to them as civil engineers and construction
managers. This can be a useful role to students who are considering multiple majors, 
and it has practical purposes for some students. However, we feel that this class can 
be made optional as its learning outcomes are not critical for all students. 

Requiring this class also creates issues for some transfer students, as courses like 
this are not typical at other schools. If we allow it to be optional, then we do 
not have to justify individual transfer exceptions for our ABET accreditation.

## CCE 102: Sustainable Infrastructure {#sec-sustainability}
::: {.callout-note}
## Proposed Change
Create CCE 102 (3 credit hours) by combining many learning outcomes from CCE 101 (1), CCE 201 (2), and CCE 231 (3)
:::

Given the limitations discussed in @sec-introcce, we desire to make an introductory
 class that *shows* how designing and building
civil infrastructure benefits society through interactive case studies and a
lens of stewardship. 

The objective of this course is not to bring in all the learning outcomes of all
three courses it replaces. Rather, we hope to create a targeted, "lean and taut"
course that looks at global challenges to human prosperity and happiness,
potential solutions to these challenges using built environments, and the responsibility
of trained Latter-day Saints to find and implement solutions to these
challenges. We hope that this class will set a tone for all the subjects
students will encounter through their programs.  Proposed learning outcomes include: 

  1. Describe how civil infrastructure and the built environment can foster (or inhibit) a sustainable society, including efforts to achieve United Nations Sustainable Development Goals. 
  2. Apply the principle of time value of money to identify financially sustainable infrastructure investment decisions. 
  3. Recognize ethical and professional responsibilities in engineering situations and make informed judgments, which must consider the impact of engineering solutions in global, economic, environmental, and societal contexts. ([ABET Student Outcome 4](https://www.abet.org/accreditation/accreditation-criteria/criteria-for-accrediting-engineering-programs-2022-2023/#GC3))
  4. Function effectively on a team whose members together provide leadership, create a collaborative and inclusive environment, establish goals, plan tasks, and meet objectives. ([ABET Student Outcome 5](https://www.abet.org/accreditation/accreditation-criteria/criteria-for-accrediting-engineering-programs-2022-2023/#GC3))

We intend that this course will qualify for the Global and Cultural Awareness
University Core requirement (focused on the global challenge of sustainability),
or as an Explorations: Science and Technology in the proposed GE.  We also
expect this change to enhance recruiting of undecided majors across campus and
begin generating interest in civil engineering and construction disciplines
students will explore later.


## CCE 117 / 118 Engineering Software and Measurements 
::: {.callout-note}
## Proposed Change
Proposed Change: Create a set of new courses introducing students to engineering software and measurements. Eliminate CCE 112 (3 credit hours) and CCE 214 (2 credit hours)
:::

The list of practical skills that engineering students need is always expanding, with new software replacing formerly essential tools (e.g. the shift from manual drafting to CAD) or creating new ones (GIS). Rather than adding and shifting course requirements as tools become available – and retaining legacy classes that have been superseded – we propose a two-course series where individual sections focus on different software and measurement techniques. 

CCE 117 is proposed as a two-credit hour software class. We anticipate a section focused on GIS and another on CAD, but others may be possible. Specific learning outcomes will vary by software, but all sections will require that students will: 

  1. Understand and explain software licensing models and how to install software. 
  2. Download technical files from web-based repositories, store the files onto local and shared computing networks, and open files in commercial engineering software. 
  3. Obtain useful guidance from software documentation and online help forums, including generative AI as appropriate. 
  4. Produce a visualization supporting an engineering design or analysis. 

CCE 118 is proposed as a one-credit hour engineering measurements class. We anticipate potential sections on surveying, remote sensing, water quality measurements, and piezoelectric sensors. The proposed learning outcomes for all sections are that students will: 

  1. Describe the purpose of data collection in engineering projects. 
  2. Describe the challenge of measurement accuracy and tolerance. 
  3. Use modern techniques to record, store, and disseminate engineering data. 
  4. Construct basic visualizations of engineering data. 

We recognize that many construction management students are likely to derive more benefit from BIM than GIS, and that the 3-hour CCE 113 class meets many critical CFM learning objectives for plan reading, etc. We anticipate allowing CE students to take that class as a substitute for CCE 117. 