# Senior Year

The learning outcomes for this year are for students to:

  - Prepare for future employment or graduate research opportunities by developing technical 
  depth in civil engineering disciplines of their choice.
  - Complete a culminating design experience.

## CE 471: Capstone 1 {#sec-capstone1}
::: {.callout-note}
## Proposed Change
Develop CE 471 into a 3-credit hour course that counts as an Advanced Written and Oral Communication GE. Eliminates WRTG 316 (3)
:::

Students currently take WRTG 316 Technical Writing to fulfil the 
[Advanced Written and Oral Communication AWOC](https://ge.byu.edu/00000173-e9b7-dc88-a5fb-fdff6ad60000/advanced-written-and-oral-communication)
University Core requirement. While the instructors are well trained in writing
pedagogy, they are not engineers, they are not consistent each semester, and
they are trying to meet the needs of diverse academic departments. Student
feedback over the years suggests that while some aspects of the course are
valuable (such as writing methods), the instructors and learning activities do
not relate well to their own disciplines, defeating many of the AWOC learning
outcomes. 
 
We propose to bring AWOC into the CE program as part of the Capstone experience.
This is something that many programs on campus have done, with the aid and 
encouragement of the English department, and there is an application process already in place.
The first Capstone semester would increase to 3 credits to accommodate the
change. The AWOC learning activities would be specific to Capstone projects or
senior thesis (see @sec-thesis): proposal writing, oral presentations,
literature reviews, resume preparation, interview skills, peer reviews, and so
on. We recommend hiring an adjunct instructor with a technical writing background
and an English degree to teach the writing portions of the course and 
aid the the capstone director. The capstone director will also have to participate in
some English department training activities.

## HONRS 499R / CE 499R: Honors or Senior Thesis {#sec-thesis}
::: {.callout-note}
## Proposed Change
Allow students completing senior theses (honors theses or mentored research
projects with substantive deliverables) to count their work as a culminating
design experience.
:::

[ABET requires](https://www.abet.org/wp-content/uploads/2022/01/2022-23-EAC-Criteria.pdf) (p. 9)

> a culminating major engineering design experience that 1) incorporates appropriate engineering standards and multiple constraints, and 2) is based on the knowledge and skills acquired in earlier course work.

We have satisfied this requirement with Capstone in the past, but
alternative projects such as honors theses and mentored research may also
qualify. Past students who completed both Capstone and an alternative experience
expressed that their alternative experience was more meaningful.  
 
At BYU, where undergraduate research is so highly valued, we ought to offer it
as a pathway to fulfilling this requirement. A senior thesis option can run
parallel to Capstone 2. Logistically, we would establish a 3-credit CE 499R
Senior Project course for such students (there is already a HONRS 499R). 
Early in the Capstone 1 course, a
senior thesis student would petition the undergraduate coordinator,
demonstrating that they have a mentor and an appropriate project that can be
publication-ready by the end of the second semester. Upon approval, this student would be 
excused from a capstone project group. Throughout the second
semester, the student would develop the project and prepare the final
deliverables. The student’s work will be evaluated by a three-member committee
consisting of the undergraduate coordinator (or honors coordinator for honors students),
the mentor, and one other faculty member to ensure that it is appropriate as a
culminating design experience.